--Informations sur les associations, les adhérents, les évènements.

PROMPT "LISTE DES ASSOS";
SELECT NOM_ASSO
FROM ASSOCIATIONS
ORDER BY NOM_ASSO;



--PB AVEC LA DATE
PROMPT "LISTE DES EVENEMENTS A VENIR";
SELECT TITRE_EVENT, LIEU, DATE_DEBUT--, NOM_ASSO, LOGIN_ADHERENT
FROM EVENEMENTS --JOIN ORGANISER ON EVENEMENTS.ID_EVENT = ORGANISER.ID_EVENT
WHERE DATE_DEBUT >= ('20-DEC-18')
ORDER BY DATE_DEBUT ASC;

--PB NO ROWS SELECTED
PROMPT "LISTE DU BUREAU D'UNE ASSO";
SELECT FONCTION, NOM_PERS, PRENOM_PERS
FROM RESPONSABLES JOIN ADHERENTS ON RESPONSABLES.LOGIN_ADHERENT = ADHERENTS.LOGIN_ADHERENT JOIN PERSONNES ON PERSONNES.ID_PERS=ADHERENTS.ID_PERS
WHERE NOM_ASSO = 'Ligue des maitres de l''espace et du temps';


PROMPT "LISTE DES COMMENTAIRES DUN EVENEMENT";
SELECT COMMENTAIRE_EVENT
FROM PARTICIPER
WHERE ID_EVENT = 1;



PROMPT "LISTE DES NEWS DUNE ASSOCIATION";
SELECT TITRE_NEWS, DATE_CREATION, TEXTE
FROM NEWS JOIN RESPONSABLES ON NEWS.ID_RESPO = RESPONSABLES.ID_RESPO
WHERE NOM_ASSO = 'Ligue des maitres de l''espace et du temps'
ORDER BY DATE_CREATION DESC;



PROMPT "LISTE DES COMMENTAIRES DUNE NEWS";
SELECT LOGIN_ADHERENT, COMMENTAIRE_NEWS
FROM COMMENTER
WHERE ID_NEWS = 1;



PROMPT "LISTE DES DERNIERES NEWS";
SELECT TITRE_NEWS, NOM_ASSO, DATE_CREATION, TEXTE
FROM NEWS JOIN RESPONSABLES ON NEWS.ID_RESPO = RESPONSABLES.ID_RESPO
ORDER BY DATE_CREATION DESC;




PROMPT "La liste des adhérents à une association à une date donnée";
SELECT LOGIN_ADHERENT
FROM COTISER
WHERE NOM_ASSO= 'BDS' AND DATE_INSCRIPTION <= '12-NOV-17' ;



PROMPT "La liste des personnes organisant un évènement";
SELECT LOGIN_ADHERENT
FROM ORGANISER
WHERE ID_EVENT = 1;



PROMPT "et celles des personnes participant à cet évènement.";
SELECT ID_PERS
FROM PARTICIPER
WHERE ID_EVENT = 1;

PROMPT "  Pour une news, on veut savoir le nombre de commentaires qui ont été postés.";
SELECT COUNT(*)
FROM COMMENTER
WHERE ID_NEWS = 1;
