--classement des évènements par la note donnée par les participants
SELECT TITRE_EVENT, AVG(NOTE) AS NOTE
FROM PARTICIPER JOIN EVENEMENTS ON PARTICIPER.ID_EVENT = EVENEMENTS.ID_EVENT
GROUP BY TITRE_EVENT
ORDER BY NOTE DESC;
