select TITRE_EVENT from EVENEMENTS;
prompt "De quel evenement voulez vous les commentaires ?"
accept s
SELECT COMMENTAIRE_EVENT
FROM PARTICIPER JOIN EVENEMENTS ON PARTICIPER.ID_EVENT = EVENEMENTS.ID_EVENT
WHERE TITRE_EVENT = &s;
