SELECT NOM_ASSO from ASSOCIATIONS;
PROMPT "De quelle association voulez vous voir les news?";
accept s
SELECT TITRE_NEWS, DATE_CREATION, TEXTE
FROM NEWS JOIN RESPONSABLES ON NEWS.ID_RESPO = RESPONSABLES.ID_RESPO
WHERE NOM_ASSO = &s
ORDER BY DATE_CREATION DESC;
